-- National and state crime: FBI annual counts, 1979 to 2023, 10 offense types, US + 50 states + DC.
SELECT a.VARIABLE_NAME, t.GEO_ID, t.DATE, t.VALUE
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FBI_CRIME_TIMESERIES t
JOIN SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FBI_CRIME_ATTRIBUTES a USING (VARIABLE)
WHERE a.VARIABLE_NAME ILIKE '%homicide%'
  AND t.GEO_ID = 'country/USA'
ORDER BY t.DATE DESC
LIMIT 10;

-- City incident logs, through mid-2026: New York, Chicago, Los Angeles, Houston, Seattle, San Francisco.
SELECT CITY, OFFENSE_CATEGORY, DATE_TRUNC('month', DATE) AS month, COUNT(*) AS incidents
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.URBAN_CRIME_INCIDENT_LOG
WHERE CITY = 'Chicago' AND DATE >= '2025-01-01'
GROUP BY 1, 2, 3
ORDER BY 3 DESC, 4 DESC
LIMIT 50;
